{{ config(materialized='view') }}

SELECT 'executive' AS module_key, 'executive' AS page_key, 'Executive Summary' AS module_label, '/executive' AS route_path, 'Executive' AS owner_domain, 8 AS primary_kpi_count, 'docs/qa/screenshots/milestone_1_executive_summary.png' AS screenshot_path, 'docs/qa/reports/executive_summary_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'data-quality' AS module_key, 'data-quality' AS page_key, 'Data Quality' AS module_label, '/data-quality' AS route_path, 'Data Quality' AS owner_domain, 7 AS primary_kpi_count, 'docs/qa/screenshots/milestone_1_data_quality.png' AS screenshot_path, 'docs/qa/reports/qa_report.md' AS qa_report_path UNION ALL
    SELECT 'workforce' AS module_key, 'workforce' AS page_key, 'Workforce' AS module_label, '/workforce' AS route_path, 'Workforce' AS owner_domain, 5 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2a_workforce_dashboard.png' AS screenshot_path, 'docs/qa/reports/workforce_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'payroll' AS module_key, 'payroll' AS page_key, 'Payroll & Cost' AS module_label, '/payroll' AS route_path, 'Payroll' AS owner_domain, 5 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2b_payroll_dashboard.png' AS screenshot_path, 'docs/qa/reports/milestone_2b_payroll_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'attendance' AS module_key, 'attendance' AS page_key, 'Attendance' AS module_label, '/attendance' AS route_path, 'Attendance' AS owner_domain, 5 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2c_attendance_dashboard.png' AS screenshot_path, 'docs/qa/reports/milestone_2c_attendance_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'compliance' AS module_key, 'compliance' AS page_key, 'Saudization & Compliance' AS module_label, '/compliance' AS route_path, 'Compliance' AS owner_domain, 6 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2d_compliance_dashboard.png' AS screenshot_path, 'docs/qa/reports/milestone_2d_compliance_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'er' AS module_key, 'er' AS page_key, 'Employee Relations' AS module_label, '/er' AS route_path, 'Employee Relations' AS owner_domain, 6 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2e_er_dashboard.png' AS screenshot_path, 'docs/qa/reports/milestone_2e_er_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'recruitment' AS module_key, 'recruitment' AS page_key, 'Recruitment & Hiring' AS module_label, '/recruitment' AS route_path, 'Recruitment' AS owner_domain, 7 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2f_recruitment_dashboard.png' AS screenshot_path, 'docs/qa/reports/milestone_2f_recruitment_qa_report.md' AS qa_report_path UNION ALL
    SELECT 'talent' AS module_key, 'talent' AS page_key, 'Talent & Succession' AS module_label, '/talent' AS route_path, 'Talent' AS owner_domain, 11 AS primary_kpi_count, 'docs/qa/screenshots/milestone_2g_talent_dashboard.png' AS screenshot_path, 'docs/qa/reports/milestone_2g_talent_qa_report.md' AS qa_report_path
