import sys
import os
import shutil
import pytest
from fastapi.testclient import TestClient

# Add backend to python path
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
)

from app.main import app
from app.api.data import get_silver_dir

client = TestClient(app)

@pytest.fixture(autouse=True)
def setup_and_teardown():
    """
    Ensure the silver directory exists, and clean up test files after run.
    """
    silver_dir = get_silver_dir()
    os.makedirs(silver_dir, exist_ok=True)
    yield
    # Cleanup test files generated by tests
    for name in ["test_employees", "test_payroll", "test_attendance"]:
        pq_path = os.path.join(silver_dir, f"{name}.parquet")
        uploaded_path = os.path.join(silver_dir, f"{name}.parquet.uploaded")
        if os.path.exists(pq_path):
            os.remove(pq_path)
        if os.path.exists(uploaded_path):
            os.remove(uploaded_path)

def test_templates_endpoints():
    # 1. List templates
    response = client.get("/api/data/templates")
    assert response.status_code == 200
    templates = response.json()
    assert isinstance(templates, list)
    assert len(templates) > 0
    assert any(t["name"] == "employees" for t in templates)

    # 2. Download template — headers only, generated from the contract.
    download_response = client.get("/api/data/templates?name=employees")
    assert download_response.status_code == 200
    assert "text/csv" in download_response.headers["content-type"]
    assert "employees_template.csv" in download_response.headers["content-disposition"]

    # 2a. The template MUST NOT contain data rows. Before Phase 1 this endpoint
    # served data/sample/employees_sample.csv — fabricated employee records —
    # as the client's onboarding artefact. Guard against that regressing.
    body = download_response.text
    rows = [r for r in body.splitlines() if r.strip()]
    assert len(rows) == 1, f"template must be header-only, got {len(rows)} rows"
    assert "EMP001" not in body and "Ahmad Al-Sudairy" not in body

    # 2b. Headers must match the contract exactly, in order.
    import yaml
    from app.api.data import get_contracts_dir
    with open(os.path.join(get_contracts_dir(), "employees_schema.yml"), encoding="utf-8") as f:
        expected = [c["name"] for c in (yaml.safe_load(f) or {})["columns"]]
    assert rows[0].strip().split(",") == expected

    # 3. Invalid template name
    invalid_response = client.get("/api/data/templates?name=nonexistent")
    assert invalid_response.status_code == 404

    # 4. A catalogued domain with no contract is reported unavailable and must
    #    fail loudly rather than fall back to sample data.
    er = next(t for t in templates if t["name"] == "employee_relations")
    assert er["available"] is False
    no_contract = client.get("/api/data/templates?name=employee_relations")
    assert no_contract.status_code == 409

def test_upload_endpoints_validation():
    # 1. Forbidden file extension
    files = {"file": ("test.txt", b"some plain text data", "text/plain")}
    response = client.post("/api/data/upload", files=files)
    assert response.status_code == 400
    assert "Only .csv and .parquet files are allowed" in response.json()["detail"]

    # 2. Path traversal attack protection
    files = {"file": ("../../test.csv", b"employee_id,employee_name\nEMP999,Hacker", "text/csv")}
    response = client.post("/api/data/upload", files=files)
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "test.parquet"
    assert ".." not in data["destination_path"]

def test_valid_csv_compilation():
    # Upload a valid CSV and verify Polars compiles it to Parquet
    csv_content = (
        "employee_id,employee_name,nationality,is_saudi,joining_date,basic_salary,housing_allowance,transport_allowance\n"
        "EMP001,Ahmad,Saudi,True,2024-01-15,12000,3000,1000\n"
    )
    files = {"file": ("test_employees.csv", csv_content.encode("utf-8"), "text/csv")}
    response = client.post("/api/data/upload", files=files)
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "test_employees.parquet"
    
    # Check that Parquet file and companion marker .uploaded file were created
    silver_dir = get_silver_dir()
    pq_file = os.path.join(silver_dir, "test_employees.parquet")
    marker_file = os.path.join(silver_dir, "test_employees.parquet.uploaded")
    
    assert os.path.exists(pq_file)
    assert os.path.exists(marker_file)
    
    # Verify .uploaded marker contents
    with open(marker_file, "r") as f:
        content = f.read()
        assert "Uploaded: test_employees.csv" in content

def test_refresh_trigger():
    # Trigger pipeline refresh via subprocess
    response = client.post("/api/data/refresh")
    assert response.status_code == 200
    data = response.json()
    assert "status" in data
    assert "return_code" in data
    assert "stdout" in data
    assert "stderr" in data
