import sys
import os
import shutil
import pytest
from fastapi.testclient import TestClient

# Add backend to python path
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
)

from app.main import app
from app.api.data import get_silver_dir

client = TestClient(app)

@pytest.fixture(autouse=True)
def setup_and_teardown():
    """
    Ensure the silver directory exists, and clean up test files after run.
    """
    silver_dir = get_silver_dir()
    os.makedirs(silver_dir, exist_ok=True)
    yield
    # Cleanup test files generated by tests
    for name in ["test_employees", "test_payroll", "test_attendance"]:
        pq_path = os.path.join(silver_dir, f"{name}.parquet")
        uploaded_path = os.path.join(silver_dir, f"{name}.parquet.uploaded")
        if os.path.exists(pq_path):
            os.remove(pq_path)
        if os.path.exists(uploaded_path):
            os.remove(uploaded_path)

def test_templates_endpoints():
    # 1. List templates
    response = client.get("/api/data/templates")
    assert response.status_code == 200
    templates = response.json()
    assert isinstance(templates, list)
    assert len(templates) > 0
    assert any(t["name"] == "employees" for t in templates)

    # 2. Download template — headers only, generated from the contract.
    download_response = client.get("/api/data/templates?name=employees")
    assert download_response.status_code == 200
    assert "text/csv" in download_response.headers["content-type"]
    assert "employees_template.csv" in download_response.headers["content-disposition"]

    # 2a. The template MUST NOT contain data rows. Before Phase 1 this endpoint
    # served data/sample/employees_sample.csv — fabricated employee records —
    # as the client's onboarding artefact. Guard against that regressing.
    body = download_response.text
    rows = [r for r in body.splitlines() if r.strip()]
    assert len(rows) == 1, f"template must be header-only, got {len(rows)} rows"
    assert "EMP001" not in body and "Ahmad Al-Sudairy" not in body

    # 2b. Headers must match the contract exactly, in order.
    import yaml
    from app.api.data import get_contracts_dir
    with open(os.path.join(get_contracts_dir(), "employees_schema.yml"), encoding="utf-8") as f:
        expected = [c["name"] for c in (yaml.safe_load(f) or {})["columns"]]
    assert rows[0].strip().split(",") == expected

    # 3. Invalid template name
    invalid_response = client.get("/api/data/templates?name=nonexistent")
    assert invalid_response.status_code == 404

    # 4. The catalogue is DERIVED from data/contracts/ (cycle 1b-ii), so it is
    #    exactly the set of contracted domains. This assertion previously
    #    checked that employee_relations was unavailable and returned 409; that
    #    was true only because the domain had no contract despite having a
    #    dashboard page, a sample file and 15 exception checks. 1b-ii authored
    #    the contract, so it now resolves like any other domain.
    import yaml as _yaml
    from app.api.data import get_contracts_dir as _gcd
    contracted = sorted(
        f[: -len("_schema.yml")]
        for f in os.listdir(_gcd()) if f.endswith("_schema.yml")
    )
    assert sorted(t["name"] for t in templates) == contracted
    assert all(t["available"] for t in templates)
    assert "hr_requests" in contracted, "contracted but previously missing from the catalogue"

    er = client.get("/api/data/templates?name=employee_relations")
    assert er.status_code == 200
    assert len([r for r in er.text.splitlines() if r.strip()]) == 1, "header only"

    # A domain with no contract has no template at all.
    assert client.get("/api/data/templates?name=not_a_domain").status_code == 404
    assert _yaml is not None

def test_upload_refuses_what_the_filename_used_to_decide():
    """P0-2 step 1. The uploaded file decides neither the format nor the table.

    Before this, `table_name = os.path.splitext(filename)[0]`, so payroll.csv
    renamed employees.csv replaced the employee master, and any file ending
    .parquet was copied byte-for-byte into data/silver.
    """
    csv_bytes = b"employee_id,employee_name" + bytes([10]) + b"EMP999,Someone"

    # 1. a table is required - it is no longer inferred from the filename
    r = client.post("/api/data/upload",
                    files={"file": ("employees.csv", csv_bytes, "text/csv")})
    assert r.status_code == 400
    assert "no longer inferred from the filename" in r.json()["detail"]

    # 2. the table must be contracted
    r = client.post("/api/data/upload?table=not_a_domain",
                    files={"file": ("employees.csv", csv_bytes, "text/csv")})
    assert r.status_code == 400
    assert "no contract" in r.json()["detail"]

    # 3. parquet is refused - NOT YET, with the precondition in the message
    r = client.post("/api/data/upload?table=employees",
                    files={"file": ("employees.parquet", b"PAR1", "application/octet-stream")})
    assert r.status_code == 400
    detail = r.json()["detail"]
    assert "not accepted yet" in detail and "dataframe" in detail

    # 4. anything else is still refused
    r = client.post("/api/data/upload?table=employees",
                    files={"file": ("test.txt", b"plain", "text/plain")})
    assert r.status_code == 400
    assert "Forbidden file type" in r.json()["detail"]


def test_refresh_trigger():
    # Trigger pipeline refresh via subprocess
    response = client.post("/api/data/refresh")
    assert response.status_code == 200
    data = response.json()
    assert "status" in data
    assert "return_code" in data
    assert "stdout" in data
    assert "stderr" in data
